# Generated by Django 5.1.2 on 2024-10-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notatki', '0002_alter_notatka_data_publikacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='notatka',
            name='poziom_waznosci',
            field=models.CharField(choices=[('malo', 'Mało ważny'), ('srednio', 'Średnio ważny'), ('bardzo', 'Bardzo ważny')], default='malo', max_length=10),
        ),
    ]
